/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "老Kin的博客",
  "description": "Just playing around",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/avatar.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Hello world!!",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4ae64dc8",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "test",
          "slug": "test"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/avatar.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "技术文档",
        "link": "/tech/interview"
      }
    ],
    "sidebar": "auto"
  }
}